### ISSUE TITLE
Unable to subscribe to any topic

### ISSUE THREAD

**Issue by lupixch** [kamilfb/mqtt-spy#49]
Every time I try to subscribe to a topic, I get the error message "Cannot subscribe to an empty topic". I can use as topic whatever I want, the behavior remains the same
I use version 0.3.0, in version 2.xx this worked without problems.
In mqtt-spy.log I see no errors or warnings.
![subscribe-problem-0 3 0](https://cloud.githubusercontent.com/assets/14980634/10284434/4a06c586-6b84-11e5-95a5-3b3606f2f943.gif)

**Comment by kamilfb** [comment]
Hi. Thanks for raising this. I've managed to reproduce it. In the meantime, please use the Enter key to subscribe rather than clicking on the Subscribe button. I'll try to fix it ASAP. Cheers

**Comment by kamilfb** [comment]
It turns out this is a bug in Oracle's JRE/JDK. See Issue 50 (https://github.com/kamilfb/mqtt-spy/issues/50) for more detail.

**Comment by kamilfb** [comment]
This should have been fixed in JRE/JDK 8 Update 66. Could you try it please?

**Comment by kamilfb** [comment]
It's JRE/JDK 8 Update 65/66.

**Comment by lupixch** [comment]
It does still not work correctly. Actually I have the following strange 
behaviour using Java(TM) SE Runtime Environment (build 1.8.0_65-b17):

 1. Type '#' in subscription topic field, click "Subscribe" -> Message box
    "Cannot subscribe to an empty topic"
 2. Press Enter (with focus in subscription topic field) -> Subscription of '#'
    is done and works
 3. Unsubscribe and close tab
 4. Type 'foo' in subscription topic field, click "Subscribe" -> Subscription of
    '*#*' is done (and works), 'foo' is not used

The click on "Subscribe" uses always the last topic that was entered using Enter 
and not the one, that is present in the input field.

**Comment by kamilfb** [comment]
Sorry - you are right - there problem is till there - my fault! Just checked the Oracle website and it looks like this fix is going to make it to JRE/JDK 8 Update 72.

**Comment by scargill** [comment]
I've just spotted this one now... yes, same thing happening to me - I'm so glad someone reported it - I'm back in the UK setting up a computer, loaded the latest MQTT-SPY and could not subscribe to anything...  at least now I know why.. do we know when this update is coming out?

**Comment by kamilfb** [comment]
JRE/JDK 8 Update 72 is scheduled for January. In the meantime, you can either press the Enter key after typing the subscription topic or go back to Update 51.

**Comment by kamilfb** [comment]
0.3.1 beta build 24 contains a workaround for the JRE bug - please let me know if that resolves the problem.

**Comment by scargill** [comment]
YUP that does it – thanks for your continued efforts – still the best out there.

**Comment by lupixch** [comment]
Yes, it works! Perfect! Thank you very much.

**Comment by kamilfb** [comment]
Fixed in 0.3.1.
